flatcar/ue-rs

.github/workflows/ci.yaml, .rustfmt.toml, omaha/src/hash_types.rs, omaha/src/lib.rs, omaha/src/request.rs, omaha/src/response.rs, omaha/src/types.rs, src/bin/download_test.rs, src/bin/full_test.rs, src/bin/request.rs, src/bin/response.rs, src/download.rs, src/request.rs
Run CI workflow for each pull request. At the moment it only runs `cargo fmt --all --check`.
Add `.rustfmt.toml` to configure rustfmt per project.
Note, it is unfortunately not possible to set `trailing_comma` option, because that is only available in Nightly toolchains.
See also the [doc](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#trailing_comma).
Disable `rustfmt` check in case of method calls that spread across multiple lines, which we would like to keep as-is, even if `rustfmt` does not provide a way to disable or configure the changes.
With disabling rustfmt checks, we are now able to run rustfmt with the following `.rustfmt.toml`.
```
max_width=200
fn_call_width=80
reorder_imports=false
use_small_heuristics="Off"
```
Fixes …
=> Run rustfmt for each PR via GitHub Actions

.github/workflows/ci.yaml, Cargo.toml, omaha/src/types.rs, omaha/src/uuid.rs
Add omaha to the list of workspaces, to be able to build and test both `src` and `omaha` by a single cargo command, like `cargo build --workspace` or `cargo test --workspace`.
Define tests module, and add all unit tests into the module, to avoid building unit tests when running cargo build.
In Github Actions, run `cargo build --workspace` and `cargo test --workspace`.
=> Make CI build and run unit tests, add workspace

Cargo.lock, update-format-crau/Cargo.toml, update-format-crau/src/bin/test.rs
Parse signatures header, check for signature versions.
Fixes https://github.com/flatcar/Flatcar/issues/1025
=> update_crau: parse signature header

README.md
Add new README.
Fixes https://github.com/flatcar/ue-rs/issues/16
=> README: add new README

.github/workflows/ci.yaml
Run CI not only for a new pull request, but also when trunk branch is pushed.
=> .github: run CI also when trunk branch is pushed

Cargo.lock
Update `rustix` to 0.38.20, mainly to address a memory explosion issue, https://github.com/advisories/GHSA-c827-hfw6-qwvm.
It is also required to update libc and linux-raw-sys.
Fixes https://github.com/flatcar/ue-rs/security/dependabot/12
=> Cargo: update rustix to 0.38.20

Cargo.lock, Cargo.toml, src/bin/download_sysext.rs, src/lib.rs, src/testdata/omaha-request-example.xml, src/testdata/omaha-response-example.xml, test/crau_verify.rs, update-format-crau/Cargo.toml, update-format-crau/src/delta_update.rs, update-format-crau/src/lib.rs, update-format-crau/src/verify_sig.rs
Move the delta update part from `test/crau_verify.rs` to `update-format-crau`.
Move `verify_sig` into `update-format-crau`, so it can be imported by delta_update.
Integrate signature verification in `download_sysext`.
=> download_sysext: integrate signature verification

Cargo.lock, Cargo.toml
Disable `full` feature of tokio, instead enable only necessary features, `macros`, `net`, `rt-multi-thread`.
Doing that, build time drops by ~10%.
See also https://github.com/flatcar/ue-rs/issues/18.
=> Cargo: optimize feature flags of tokio

Cargo.lock, Cargo.toml, omaha/src/hash_types.rs, src/bin/download_sysext.rs, test/crau_verify.rs, update-format-crau/Cargo.toml, update-format-crau/src/delta_update.rs, update-format-crau/src/verify_sig.rs
In update-format-crau, we should check error from `verify_rsa_pkcs` to handle errors correctly.
Fix bugs when reading from File to buffer. We need to first create a BufReader for reading from the buffer, pass that into parsing functions. That would make the code much easier to maintain, instead of passing File itself. Then we can read data without having to first open the file and track read positions.
We need to introduce get_header_data() to read header and data, setting the begining of the stream including the whole data including delta update header as well as manifest. Doing that, signature verification works well.
Also introduce get_data_blob() to read only data without header, manifest.
We need to skip checking for existing downloads, if the file does not exist. Otherwise, …
=> Fix signature verification, check_download

src/bin/download_sysext.rs, src/download.rs
Define `DownloadFailed` status, and check for errors of HTTP client.
Check for HTTP status codes for immediate failures in `download_and_hash`, for now only `403 Forbidden` and `404 Not found`.
Fixes https://github.com/flatcar/ue-rs/issues/14.
=> download_sysext: check for download failure

Cargo.lock, Cargo.toml, examples/full_test.rs, examples/request.rs, examples/response.rs, omaha/Cargo.toml, omaha/src/hash_types.rs, omaha/src/response.rs, src/bin/download_sysext.rs, src/download.rs, src/request.rs, test/crau_verify.rs, update-format-crau/Cargo.toml, update-format-crau/src/delta_update.rs, update-format-crau/src/verify_sig.rs
Add a new dependency of `anyhow` crate, to use flexible concrete error handling mechanism, instead of the native error types.
To follow error handling convention of anyhow, insert `.context` to add detailed message of error context when returning from functions.
In case of an immediate error exit, use a `bail!` macro.
Note, main functions and unit tests stay untouched if possible.
Fixes https://github.com/flatcar/ue-rs/issues/25
=> migrate error handling to anyhow

src/bin/download_sysext.rs, test/crau_verify.rs, update-format-crau/src/delta_update.rs
To deal with signature verification errors in a detailed way, let's change return type of `parse_signature_data` functions back to `Result`.
Iterate over signature slots to find a valid signature. If not found, return Error.
See also https://github.com/flatcar/ue-rs/issues/28
=> Change return types to Result in signature verification

examples/download_test.rs, src/bin/download_sysext.rs, src/download.rs, src/lib.rs, test/crau_verify.rs
To be able to handle HTTP redirects, we need to create reqwest Client with its Client builder, which defaults to 10 attempts on redirects.
Then it is not necessary to do anything again after receiving HTTP response.
Fixes https://github.com/flatcar/ue-rs/issues/27
Fixes https://github.com/flatcar/ue-rs/issues/17
=> Handle HTTP redirects using reqwest Client builder

examples/response.rs, omaha/src/hash_types.rs, omaha/src/response.rs, src/bin/download_sysext.rs, src/request.rs, test/crau_verify.rs
Address issues reported by `cargo clippy`.
* Remove unnecessary `use omaha`.
* Remove `'static` for const strings.
* Use `Some(h)` instead of map().
* Remove `map(f)` on an Option value where f is a closure that returns unit type ().
* Deref would be done by auto-deref.
* Remove unneeded `return`.
* Use if instead of match in case of equility checks.
* Remove redundant pattern matching, use `is_some()`.
* Use `From<Hash<T>> for Vec<u8>` instead of `Into<Vec<u8>> for Hash<T>`.
* Remove unnecessary `Ok` and question mark.
Note: issues in `vendor/hard-xml*` are not touched.
Fixes https://github.com/flatcar/ue-rs/issues/32
=> Remove clippy warnings

Cargo.toml
The release binary should be as small as possible without impact. Since this is new code we also want the release binary to still have overflow checks instead of silently eating them.
Add a release profile that strips the debug symbols, uses one codegen unit to get similar gains as thin LTO (which we seem to have cross- compiling problems with), and enable overflow checks.
=> Cargo.toml: Add release profile for smaller size and overflow checks

examples/download_test.rs, examples/full_test.rs, src/bin/download_sysext.rs, src/download.rs
For scripting the current progress report is too verbose. Add a flag to opt-in.
Add `--print-progress` if wanted
Default behavior is no output. With `--print-progress` the report works as before.
Fixes https://github.com/flatcar/ue-rs/issues/38
=> download: Make progress reporting opt-in

Cargo.lock, Cargo.toml, examples/download_test.rs, examples/full_test.rs, examples/request.rs, src/bin/download_sysext.rs, src/download.rs, src/request.rs
Seems to work :)
Agree if we want to use this 
Downloading with a direct URL and with the XML works. I also checked that the download is done to disk and there is no copy in RAM (/usr/bin/time -v shows the Maximum resident set size to be 24 MB for the full Flatcar update payload which is 370 MB).
=> Switch to reqwest::blocking

src/bin/download_sysext.rs, src/download.rs, src/lib.rs, src/util.rs
Set the default timeout to 20 seconds, so HTTP client can abort after that timeout.
If HTTP client fails to download, retry to download once in 1000 msec, up to 20 times.
Fixes https://github.com/flatcar/ue-rs/issues/15
=> download_sysext: HTTP client timeout and retry

src/bin/download_sysext.rs
The download can hang for longer time if, e.g., the route goes down. To error out more quickly, enable the TCP keepalive option.
Disabled the wifi and after a longer time, because the retries also take longer due to DNS failures, we get a DNS failure from the last retry.
=> download_sysext: Set TCP keepalive option

src/bin/download_sysext.rs, src/download.rs, test/crau_verify.rs, update-format-crau/src/delta_update.rs
- download: Remove unused seek to 0
The file is freshly opened and already at offset 0.
- Use explicit offsets for reading and writing
Currently the order in which the functions are called matters because
they advance the offset. Some had seeks but not all.
Use explicit read and write offsets to make the code more robust. Also,
we have to make use of the start_block to calculate the destination even
if we didn't ran into a problem yet because the way we generate the
payload was giving the order we happened to write out.
The generic payload and the sysext payload extracts as usual.
=> Use explicit offsets for reading and writing

.github/workflows/ci.yaml, Cargo.lock, examples/download_test.rs, examples/full_test.rs, omaha/Cargo.toml, omaha/src/hash_types.rs, src/bin/download_sysext.rs, src/download.rs, src/lib.rs, src/request.rs, test/crau_verify.rs, vendor/hard-xml-derive/src/lib.rs, vendor/hard-xml/src/lib.rs
- Check Omaha sha1 hash if available
Old Nebraska servers were missing the newly introduced sha256 attribute and might only serve paylads with the regular sha1 attribute set. The generic payload is also just using the regular sha1 attribute because at that time a different extension was used which holds the sha256 checksum for the generic payload.
Support the regular Omaha sha1 hash for use with old Nebraska servers. This makes it also easy to test with the generic payload.
- Verify checksum after download, with retry
The self.verify_checksum(...) call's return value wasn't checked in the
package download call. Even if we do it there we should rather move it
into the retry loop and make it explicit whether we expect certain
checksums or not.
Check the checksum after the download, and also …
=> Check Omaha sha1 hash if available and Verify checksum after download, with retry

src/bin/download_sysext.rs
When a match pattern has to be used, the resulting filename in the output directory is unknown.
Add parameters to take only the first match and use a particular name for the extracted target file.
Should fix the problem with self-hosted update payloads.
In [scripts PR with Flatcar](https://github.com/flatcar/scripts/pull/1580) and also manual:
```
target/debug/download_sysext -p ~/kinvolk/scripts/sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-au-key/files/official-v2.pub.pem -m "*oem-azure.gz" -o /var/tmp/outdir/ -i /var/tmp/beta-response-local -v -n oem-azure.raw -t
```
where the XML has entries like `<package name="extrafile-amd64-3815.0.0-oem-ami.gz" …`
=> Add parameters to specify target filename

.github/workflows/ci.yaml
To make the CI correctly work when running cargo clippy, an additional option `-- --deny warnings` is needed.
Without that, cargo clippy would always succeed, so CI is not able to check its result.
=> .github: cargo clippy with --deny warnings option

Cargo.lock, Cargo.toml
Update h2 to `0.3.26`, to address HTTP/2 CONTINUATION flood issues.
Update related crates as well, reqwest to `0.11.26`, hyper to `0.14.28`, which are only patchlevel updates.
See also https://rustsec.org/advisories/RUSTSEC-2024-0332.html, https://nowotarski.info/http2-continuation-flood/, https://seanmonstar.com/blog/hyper-http2-continuation-flood/.
=> Cargo: update h2 to 0.3.26 to fix HTTP/2 CONTINUATION flood

Cargo.lock, Cargo.toml
Remove unnecssary crates, `bzip2` and `protobuf`. Detected by `cargo-machete`.
For some reason cargo-machete shows false positive of uuid, which is actually needed for building ue-rs. Exlude uuid from machete.
=> Cargo.toml: remove unnecessary crates bzip2, protobuf

omaha/src/response.rs, src/bin/download_sysext.rs, src/download.rs, src/request.rs, test/crau_verify.rs, update-format-crau/src/delta_update.rs, update-format-crau/src/verify_sig.rs
Starting from Rust 1.88, clippy prints out warnings in case of uninlined format arguments in format strings.
Fix them to unblock CI.
```
error: variables can be used directly in the `format!` string
Error:   --> omaha/src/response.rs:70:29
|
70 |             _ => return Err(format!("unknown success action \"{}\"", s)),
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
= note: `-D clippy::uninlined-format-args` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::uninlined_format_args)]`
help: change this to
|
70 -             _ => return Err(format!("unknown success action \"{}\"", s)),
70 +             _ => return …
```
=> *: fix clippy issues with Rust 1.88+.

.github/workflows/ci.yaml
Moved to [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) due to deprecated apis with action-rs
Used act&docker to run the actions locally
=> fix: migrated from action-rs to dtolnay/rust-toolchain@stable

src/util.rs
There is currently only one function in the `util` module: `retry_loop()`. This PR improves this function (and therefore module) in that it:
- Adds unit tests for `retry_loop()` as per #77. 
- Adds a docstring with a usage example as per #78.
- Rewrites the function slightly to be more readable and rusty.
=> Util Module Improvements

src/bin/download_sysext.rs, src/download/mod.rs, src/lib.rs
Before PR https://github.com/flatcar/ue-rs/pull/87, `target_filename` was almost always `None`, which had hidden an issue of setting `pkg_verified`. In case of `target_filename` being a valid String, for example `oem-azure.gz`, `pkg_verified` ended up having an extension `.gz`, which is not expected.
Now that the PR was merged, DownloadVerify module gets created with `.target_filename(args.target_filename.unwrap_or(TARGET_FILENAME_DEFAULT.into()))`, where `TARGET_FILENAME_DEFAULT` is with `.gz` extension. That uncovered the hidden issue.
Fix that with explicitly setting extension `.raw` for both a valid String and None for the input string.
Since the target filename could vary for many update payload types and OEMs, it does not make sense to set a default filename to a specific target …
=> download: Fix bug of pkg_verified path extension
